{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"spotify-2023\",\"Date_Soptify\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.2028.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 2/23/2024 6:35:05 PM.",
        "folder": "Query Errors - 2/23/2024 6:35:05 PM"
      }
    ],
    "relationships": [
      {
        "name": "5b36979a-9cf9-437e-9529-cc6edf58ba30",
        "fromColumn": "Date",
        "fromTable": "spotify-2023",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7c0617d7-4a73-43c5-943f-af75cee73a49"
      },
      {
        "name": "1701c4d9-26b3-4b14-9ea5-f82dd3d235ca",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Date",
        "fromTable": "Date_Soptify",
        "toCardinality": "many",
        "toColumn": "Date",
        "toTable": "spotify-2023"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "spotify-2023",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "track_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34c54a16-3ae6-4183-bb6c-07759b285fc3",
            "sourceColumn": "track_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist(s)_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4897917c-7721-4ced-9975-f220740d69b9",
            "sourceColumn": "artist(s)_name",
            "summarizeBy": "none"
          },
          {
            "name": "artist_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c3719ab-e2a7-44b2-ae72-424d4fc62a6c",
            "sourceColumn": "artist_count",
            "summarizeBy": "sum"
          },
          {
            "name": "released_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ad849ea2-ae0e-4852-a254-f64ec96a47d6",
            "sourceColumn": "released_year",
            "summarizeBy": "sum"
          },
          {
            "name": "released_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b45d2814-a73a-4a36-9eec-949d4c87345d",
            "sourceColumn": "released_month",
            "summarizeBy": "sum"
          },
          {
            "name": "released_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74b6455f-1c22-4bd9-98ae-7a87cc78bea7",
            "sourceColumn": "released_day",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "537288f1-a4ba-4fbe-8684-66be44fb0bdd",
            "sourceColumn": "in_spotify_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_spotify_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0a53b71-7954-40c1-95cc-4e20052cc245",
            "sourceColumn": "in_spotify_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "streams",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b83999e-6a80-46ff-8389-6c8c48428e87",
            "sourceColumn": "streams",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7217f14d-f12b-4eb6-8473-51e949fb32ed",
            "sourceColumn": "in_apple_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_apple_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e4c9a9c-2139-4517-8253-7db52b7c1ec0",
            "sourceColumn": "in_apple_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_playlists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e647d3b-f4e2-408d-9a42-c4ce9d744a1e",
            "sourceColumn": "in_deezer_playlists",
            "summarizeBy": "sum"
          },
          {
            "name": "in_deezer_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d6821235-8b0f-45db-a656-076e722b6690",
            "sourceColumn": "in_deezer_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "in_shazam_charts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "988c5311-6210-4ca1-bc75-62467a74c5f3",
            "sourceColumn": "in_shazam_charts",
            "summarizeBy": "sum"
          },
          {
            "name": "bpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c35c4ef5-d8f0-41f9-a801-b2e4d401ac21",
            "sourceColumn": "bpm",
            "summarizeBy": "sum"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "951e47d5-f4e7-468b-9937-161a28f5ec37",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "mode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2045d3f-2b74-42fd-9b5d-43bd8ee82c92",
            "sourceColumn": "mode",
            "summarizeBy": "none"
          },
          {
            "name": "danceability_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "588b46c3-73ba-49f1-8684-f80a4fb9fc22",
            "sourceColumn": "danceability_%",
            "summarizeBy": "sum"
          },
          {
            "name": "valence_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f89f4131-6389-4a32-a386-92180044b69c",
            "sourceColumn": "valence_%",
            "summarizeBy": "sum"
          },
          {
            "name": "energy_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3729387-f6a2-4a19-8967-16fb26d40659",
            "sourceColumn": "energy_%",
            "summarizeBy": "sum"
          },
          {
            "name": "acousticness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "08aa6d64-b3ff-445e-8c0f-85b88c1a06a3",
            "sourceColumn": "acousticness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "instrumentalness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f34804ab-56b0-4944-851b-2d2efdef095e",
            "sourceColumn": "instrumentalness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "liveness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b319f88e-cfcc-4d23-888e-6a58848ef05e",
            "sourceColumn": "liveness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "speechiness_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b3b527d-bafd-4c38-b87d-5326f73d86ab",
            "sourceColumn": "speechiness_%",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE([released_year],[released_month], [released_day])",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "c26fbb52-4266-4698-8951-3d2b129f9e09",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_7c0617d7-4a73-43c5-943f-af75cee73a49"
                },
                "isDefault": true,
                "relationship": "5b36979a-9cf9-437e-9529-cc6edf58ba30"
              }
            ]
          }
        ],
        "lineageTag": "745720e4-d824-4b5f-98a7-86d78deac146",
        "measures": [
          {
            "name": "_Max streams",
            "expression": "MAX('spotify-2023'[streams])",
            "formatString": "0",
            "lineageTag": "3f6557b0-1c82-42f0-bbf7-6ee18f3e7eed"
          },
          {
            "name": "_Top songs streams",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('spotify-2023'[streams]),",
              "    'spotify-2023'[streams] = MAX ('spotify-2023'[streams]))"
            ],
            "formatString": "0",
            "lineageTag": "db5b6c91-49b8-4039-9663-33e27bb815cd"
          },
          {
            "name": "_Average Streams per year",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE('spotify-2023'[streams]),",
              "    ALLEXCEPT('spotify-2023', 'spotify-2023'[Date])",
              ")"
            ],
            "lineageTag": "d7464c09-1cb1-4169-afe3-05cf3dc6917b"
          },
          {
            "name": "_Top song vs avg val",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "DIVIDE(",
              "    [_Top songs streams]-[_Average Streams per year],",
              "    [_Average Streams per year]",
              ")"
            ],
            "lineageTag": "ece0044f-d2ce-4a95-88de-6ded275931f6"
          },
          {
            "name": "_Top song vs AVG",
            "expression": [
              "",
              "VAR x =[_Top song vs avg val] RETURN",
              "",
              "IF(x > 0,",
              "FORMAT(x, \"#.0%\") &  \" \" & UNICHAR (9650),",
              "FORMAT(x, \"#.0%\") &  \" \" & UNICHAR (9660))"
            ],
            "lineageTag": "f3be40be-6188-4b58-b64c-b9353987cfa3"
          }
        ],
        "partitions": [
          {
            "name": "spotify-2023",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Sanket_Data_Science\\Kaggle_Datasets\\spotify-2023.csv\"),[Delimiter=\",\", Columns=24, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"track_name\", type text}, {\"artist(s)_name\", type text}, {\"artist_count\", Int64.Type}, {\"released_year\", Int64.Type}, {\"released_month\", Int64.Type}, {\"released_day\", Int64.Type}, {\"in_spotify_playlists\", Int64.Type}, {\"in_spotify_charts\", Int64.Type}, {\"streams\", Int64.Type}, {\"in_apple_playlists\", Int64.Type}, {\"in_apple_charts\", Int64.Type}, {\"in_deezer_playlists\", Int64.Type}, {\"in_deezer_charts\", Int64.Type}, {\"in_shazam_charts\", Int64.Type}, {\"bpm\", Int64.Type}, {\"key\", type text}, {\"mode\", type text}, {\"danceability_%\", Int64.Type}, {\"valence_%\", Int64.Type}, {\"energy_%\", Int64.Type}, {\"acousticness_%\", Int64.Type}, {\"instrumentalness_%\", Int64.Type}, {\"liveness_%\", Int64.Type}, {\"speechiness_%\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_43cfcc98-3b44-4e2a-a084-0cc9905925d3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ad2c5e33-0abe-4bd7-af4b-a8ec55b96850",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1e6c2d00-4878-46b1-8429-39bfb3204958",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "be048fb0-234e-4d6a-89ff-3d2b96162ec7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3cf7e4bf-a3e2-4b0a-897f-05383576acc1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "96c5e75a-01eb-4455-99da-e3ebfc6f8610",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4db54f0c-7b7d-4d2e-8976-7e6f30ce2e33",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "62f3a55e-788e-45c2-a922-f0e50e06f4fe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "69fd617e-8c74-4087-90c6-66e32a189b4c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9637b7ca-e0a0-4e5a-aa35-f46a82a7cfb5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "df138981-74e5-497c-8772-5d62159bcb92",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a368bef0-bdbd-403b-ba5f-74b887597c78",
                "ordinal": 3
              }
            ],
            "lineageTag": "a355d6a4-07b8-4eab-9a7e-bbf832c95334"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0e69f9db-1136-47d7-b8cc-932672e3b55b",
        "partitions": [
          {
            "name": "DateTableTemplate_43cfcc98-3b44-4e2a-a084-0cc9905925d3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7c0617d7-4a73-43c5-943f-af75cee73a49",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "61f0ccad-dcc1-457c-b861-0fcdd24dce95",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91563c6d-2170-4a8e-bf8e-165032e28dd4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7080512-1944-4d1d-bc08-c14412eb1097",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "63ca34f3-56ac-4797-aa38-450d69bc1620",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08c68c0d-5d9c-4f64-a355-e130d0fa9e55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5ebad430-697c-42c2-95f9-d435c27465a1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "25e60cac-d694-4b4d-b780-70c99a0fc88a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6e9d53d1-8cff-43d7-90f1-516214e6cb47",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "74c50b48-cd78-49b6-ab8f-bd513ae3b951",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5d594ec6-7db2-4c82-8c0c-f887481d9cf5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0d58d7b2-4ef1-417a-8b70-5a1aa15c710a",
                "ordinal": 3
              }
            ],
            "lineageTag": "d9e7aede-d43b-4990-afc3-2d7b555e458f"
          }
        ],
        "isHidden": true,
        "lineageTag": "174bee12-f216-4990-b682-d61e059b2b0c",
        "partitions": [
          {
            "name": "LocalDateTable_7c0617d7-4a73-43c5-943f-af75cee73a49",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('spotify-2023'[Date])), 1, 1), Date(Year(MAX('spotify-2023'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Date_Soptify",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "released_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "13c66249-a596-4e31-8336-e6428e3ebde9",
            "sourceColumn": "released_year",
            "summarizeBy": "sum"
          },
          {
            "name": "released_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5dcdce9c-58e7-4d1a-af77-9c8cbff7d9b8",
            "sourceColumn": "released_month",
            "summarizeBy": "sum"
          },
          {
            "name": "released_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00b2da24-ad61-4d19-ad5d-4e57f8989c7b",
            "sourceColumn": "released_day",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATE ([released_year], [released_month],[released_day])",
            "formatString": "m/d/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "0645a9b7-2e83-4205-9275-1837a7fac371",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "4dbbb666-8ddd-4b2c-b2ca-bd014f793885",
        "partitions": [
          {
            "name": "Date_Soptify",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"D:\\Sanket_Data_Science\\Kaggle_Datasets\\Date_Soptify.csv\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"released_year\", Int64.Type}, {\"released_month\", Int64.Type}, {\"released_day\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}